### PR TITLE
Add inputRef prop

### PR DESCRIPTION
**Pull request by Jkaveri**
Exposes the react native's TextInput.

#255 #44

### CODE REVIEW

**Comment by JulianKingman** [comment]
Can this be merged? This is a super important PR for things like navigating between fields, and focusing/blurring fields programmatically.

**Comment by zrumenjak** [comment]
@Jkaveri thanks for the PR, but we have plans to address this issue in a different way. I would like to expose all the methods from the underlying `TextInput` component on the connected component, so that it could be used in the same way that the original `TextInput` is used, i.e., by just capturing the ref to it and calling method on that object.

We have started testing this approach in a limited number of cases, you can see examples in https://github.com/shoutem/ui/blob/develop/components/ScrollView/ScrollView.js#L88. Ideally we would like to implement a helper function (`hoistMethods`) that would work similarly to `hoistStatics`, but just for methods.

This function would:
* go through all the methods of the underlying component
* create the methods with the same name on the target component that call the original methods on the ref to the underlying component

With this method implemented, we could solve all the related issues for ScrollView, ListView, and any other React Native component that has instance methods.

I will close this PR, it would great if you could implement something like this, if you have time. Feel free to contact me if you have any questions.

**Comment by JulianKingman** [comment]
Will this work? https://github.com/elado/hoist-non-react-methods

**Comment by zrumenjak** [comment]
@JulianKingman we need something similar to the package that you linked. That package has two issues that I can see:
1. It hoists static methods, and throws an error if the method already exists
  `connect` from redux (and many other HoC implementations) already do this using `hoistStatics`, 
  and this results in errors if you start using this package when there are components in the 
  hierarchy with already hoisted statics.

2. It trows an error when a method already exists on the target class
  It would be better to simply skip those methods, because it was probably implemented on the 
  target class  to override the underlying behaviour.

`hoist-non-react-methods` would probably work, if it ignored statics, and methods that already exist.

**Comment by JulianKingman** [comment]
I've made a fork that solves 1, I'll add a check for 2 and try to get it merged.

**Comment by JulianKingman** [comment]
I finally got around to making the PR, you can test with my fork: https://github.com/DesignmanIO/hoist-non-react-methods, hopefully it gets merged soon.

**Comment by JulianKingman** [comment]
@zrumenjak The upstream repo has been updated, but I tried just 'tossing it in', and couldn't quite figure it out. Can you take a look?
https://github.com/elado/hoist-non-react-methods/

**Comment by dodsky** [comment]
@JulianKingman I'll take a look and see if we can leverage that package, it seems that both concerns have been fixed:
 1: https://github.com/elado/hoist-non-react-methods/blob/master/src/index.js#L52 hoist statics is now optional
2: already defined methods won't get hoisted https://github.com/elado/hoist-non-react-methods/blob/master/src/index.js#L78

**Pull request closed without merging**
