### PR TITLE
Remove examples

### PR DESCRIPTION
**Pull request by ltatarev**
Feature removes `examples` dir, updates readme, and removes remaining references to examples.
Additionally, removed `nativeDependencies` export from `const`, since the variable doesn't exist (noticed due to lint error).

### CODE REVIEW

**Review by Definitely-Not-Vlad — APPROVED** [review]
How come we're removing this? Debloat or?

**Comment by ltatarev** [comment]
> How come we're removing this? Debloat or?

We agreed to do this a while ago on a weekly meeting? :D 
If I remember correctly, the main reason was that they aren't maintained, and that it would be nicer to go in a storybook direction

**Comment by Definitely-Not-Vlad** [comment]
Ah, I figured we'd remove them after adding storybook but this works I guess.

**Review by sstimac — APPROVED** [review]
bello, bello indescrivibile

**Pull request merged**
